#! /bin/bash

if [ $# -lt 5 ]; then
   echo "usage : $0 proj_path proj_name usr_name usr_email www (without http:// !!)"
   exit 1
fi

DST=$1
PROJ=$2
NAME=$3
EMAIL=$4
WWW=$5

SELF=$(readlink -f $0)
SRC=${SELF%/*}

PROJ_U=$(echo "$PROJ" | sed 's/.*/\u&/')
PROJ_UU=$(echo "$PROJ" | sed 's/.*/\U&/')
PROJ_LL=$(echo "$PROJ" | sed 's/.*/\L&/')

[ -d $DST ] && exit 1

git clone $SRC $DST && cd $DST && rm -fr .git ${SELF##*/} || exit 1

git init && git add . || exit 1

echo "" > description
for file in $(git ls-files); do
   [ "$file" = ".gitignore" ] && continue
   echo "$file" | grep -qE '^m4' && continue
   sed -i "s/enotes/${PROJ_LL}/g;s/Enotes/${PROJ_U}/g;s/SKELETON/${PROJ_UU}/g;s/Cedric Bail/${NAME}/ig;s/cedric.bail@samsung.com/${EMAIL}/g;s/www.enlightenment.org/${WWW}/g" $file
done

for file in $(find -name '*enotes*'); do
   name=$(echo "$file" | sed "s/enotes/${PROJ_LL}/")
   mv $file $name
done
for file in $(find -name '*Enotes*'); do
   name=$(echo "$file" | sed "s/Enotes/${PROJ_U}/")
   mv $file $name
done

grep --color=auto -R FIXME .
